- hosts: ["127.0.0.1"]
  tasks:
    - name: Granting permission to the inventory
      shell: "chmod +x /root/Ansible-HAProxy/dynamic_inventory/* "
  roles:
    - name: "Provisioning Instances for the Nodes"
      role: provision-node
      
    - name: "Provisioning Instance for Load Balancer"
      role: provision-lb
  
  




    

