---
# tasks file for httpd-installation
- name: Installing httpd
  package:
    name: httpd
    state: present

- name: Starting httpd 
  service:
    name: httpd
    state: started

- name: Copy html files in Nodes
  template: 
    src: index.html
    dest: /var/www/html/index.html


